branches:
  except:
    - gh-pages

sudo: required
language: minimal

addons:
  apt:
    update: true
    packages:
      - libhunspell-1.3-0
      - libhunspell-dev
      - libextutils-pkgconfig-perl
before_install:
  - curl https://raw.githubusercontent.com/JJ/Test-Text/master/data/Spanish.aff -o Spanish.aff
  - curl https://raw.githubusercontent.com/SublimeText/Dictionaries/master/Spanish.dic -o Spanish.dic

script: perl -MTAP::Harness -e 'use utf8; my $harness = TAP::Harness->new( { verbosity => 0} ); die "FAIL" if  $harness->runtests( "just_check.t" )->failed;'

