branches:
  except:
    - gh-pages

sudo: required
language: minimal

addons:
  apt:
    update: true
    packages:
      - libhunspell-1.3-0
      - libhunspell-dev

before_install:
  - curl https://raw.githubusercontent.com/JJ/Test-Text/master/data/Spanish.aff -o Spanish.aff
  - curl https://raw.githubusercontent.com/SublimeText/Dictionaries/master/Spanish.dic -o Spanish.dic
  - echo "use Test::Text;just_check( 'documentos/temas','.', 'Spanish', 0 );just_check( 'documentos/proyecto','.', 'Spanish',1 );" > just_check.t
install: sudo cpanm  ExtUtils::PkgConfig Test::Text TAP::Harness
script: perl -MTAP::Harness -e 'use utf8; my $harness = TAP::Harness->new( { verbosity => 0} ); die "FAIL" if  $harness->runtests( "just_check.t" )->failed;'

